import type { Metadata } from "next";

import "./globals.css";
import NavBar from "./components/NavBar/Navbar";
import LoginModal from "./components/modals/LogInModal"
import SignUpModal from "./components/modals/SignUpModal";
import AddPropertyModal from "./components/modals/AddPropertyModal";
import SearchModal from "./components/modals/SearchModal";



export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const content = (<p>Some content</p>)

  return (
    <html lang="en">

      <body>
        <NavBar />
        <div className="pt-32">
          {children}
        </div>
        <SearchModal />
        <LoginModal />
        <SignUpModal />
        <AddPropertyModal />
      </body>
    </html>
  );
}
